# proto-file: github.com/impeccableai/impeccable/proto/workflow/workflow.proto
# proto-message: Task

uuid: "3053461e-c004-45fc-8631-67b95458363e"
name: "Train Sklearn model"
description: "This Task trains a scikit-learn model using either a Decision Tree Classifier or a Gradient Boosting Classifier. It reads a CSV file with training data and saves a trained model to a file."
version: "1.1"
tags: "sklearn"
python_script: {
  source: {
    raw: {
      source_uuid: "train.py"
      source_name: "train.py"
    }
  }
}
inputs: {
  id: "aa"
  name: "train_set"
  data_kind: FS_FILE
  data_hint: STRUCTURED_TEXT
}
outputs: {
  id: "bb"
  name: "trained_model"
  data_kind: FS_FILE
  data_hint: BINARY
}
default_runtime: {
  python_script_runtime: {
    docker_image: "python:latest"
    command: "python {{ script_path }} {{ train_set }} {{ trained_model }}"
  }
  new_parameters: {
    key: "y_column"
    value: {
      optional: false
      value: "Y"
    }
  }
  new_parameters: {
    key: "classifier"
    value: {
      optional: false
      value: "DecisionTreeClassifier"
    }
  }
  new_parameters: {
    key: "max_depth"
    value: {
      optional: false
      value: "10"
    }
  }
  new_parameters: {
    key: "n_estimators"
    value: {
      optional: false
      value: "50"
    }
  }
  new_parameters: {
    key: "random_seed"
    value: {
      optional: false
      value: "42"
    }
  }
  new_parameters: {
    key: "delimiter"
    value: {
      optional: false
      value: ","
    }
  }
}