# proto-file: github.com/impeccableai/impeccable/proto/workflow/workflow.proto
# proto-message: Task

uuid: "gcs_generator"
name: "GCS generator"
python_script: {
  source: {
    raw: {
      source_uuid: "source"
      source_name: "script.py"
    }
  }
}
outputs: {
  id: "a"
  name: "output"
  data_kind: GCS_FILE
}
default_runtime: {
  python_script_runtime: {
    docker_image: "python:latest"
    command: "{{ script_path }}/entrypoint.sh {{ script_path }}"
  }
}