# proto-file: github.com/impeccableai/impeccable/proto/workflow/workflow.proto
# proto-message: Task

uuid: "7bb7c4c0-80c3-45db-a6e9-d0b934263314"
name: "Tensorboard test"
description: "This Task demonstrates the use of Tensorboard by logging the sine function values for 100 steps. If a logging directory is provided, the Task will create a Tensorboard file writer and log the sine values. Additionally, it writes a string \"so ML, much AI\" to the output model file."
version: "1.0"
tags: "tensorflow"
python_script: {
  source: {
    raw: {
      source_uuid: "script.py"
      source_name: "script.py"
    }
  }
}
outputs: {
  id: "aa"
  name: "model"
  data_kind: FS_FILE
}
outputs: {
  id: "cc"
  name: "logdir"
  data_kind: FS_DIR
}
default_runtime: {
  python_script_runtime: {
    docker_image: "tensorflow/tensorflow:latest"
    command: "python {{ script_path }} --model {{ model }} --logdir {{ logdir }}"
  }
}