# proto-file: github.com/impeccableai/impeccable/proto/workflow/workflow.proto
# proto-message: Task

uuid: "tfboard"
name: "Tensorboard test"
description: ""
version: "1.0"
python_script: {
  source: {
    raw: {
      source_uuid: "script.py"
      source_name: "script.py"
    }
  }
}
outputs: {
  id: "aa"
  name: "model"
  data_kind: FS_FILE
}
outputs: {
  id: "cc"
  name: "logdir"
  data_kind: FS_DIR
}
default_runtime: {
  python_script_runtime: {
    docker_image: "tensorflow/tensorflow:latest"
    command: "python {{ script_path }} --model {{ model }} --logdir {{ logdir }}"
  }
}