# proto-file: github.com/impeccableai/impeccable/proto/workflow/workflow.proto
# proto-message: Task

uuid: "family_01"
name: "family - child task 1"
version: "1.1"
parent_uuid: "family_00"
state: TASK_STATE_DEPRECATED
python_script: {
  source: {
    raw: {
      source_uuid: "generator.py"
      source_name: "script.py"
    }
  }
}
outputs: {
  id: "aa"
  name: "output"
  data_kind: FS_FILE
}
default_runtime: {
  python_script_runtime: {
    docker_image: "python:alpine"
    command: "python {{ script_path }}"
  }
}