# proto-file: github.com/impeccableai/impeccable/proto/workflow/workflow.proto
# proto-message: Task

uuid: "dd61fd51-d274-443b-b62b-34e17c511df3"
name: "Counter"
description: "This script counts the number of lines in an input file and prints the count. The input file is specified as a command line argument using the \"input\" flag."
python_script: {
  source: {
    raw: {
      source_uuid: "script.py"
      source_name: "script.py"
    }
  }
}
inputs: {
  id: "aa"
  name: "input"
  data_kind: FS_FILE
}
default_runtime: {
  python_script_runtime: {
    docker_image: "python:alpine"
    command: "python {{ script_path }}"
  }
}