# proto-file: github.com/impeccableai/impeccable/proto/workflow/workflow.proto
# proto-message: Task

uuid: "counter"
name: "counter"
python_script: {
  source_uuid: "script.py"
  source_name: "script.py"
  source: {
    raw: {
      source_uuid: "script.py"
      source_name: "script.py"
    }
  }
}
inputs: {
  id: "aa"
  name: "input"
  data_kind: FS_FILE
}
default_runtime: {
  python_script_runtime: {
    docker_image: "python:alpine"
    command: "python {{ script_path }}"
  }
}