# proto-file: github.com/impeccableai/impeccable/proto/workflow/workflow.proto
# proto-message: Task

uuid: "27d6c1b3-32c2-44d2-aaba-f1a4a3cf46a8"
name: "SQL Query"
sql: {
  source: {
    raw: {
      source_uuid: "query.sql"
      source_name: "query.sql"
    }
  }
}
outputs: {
  id: "data"
  name: "data"
  data_hint: DATA_HINT_NONE
  data_kind: FS_FILE
}
default_runtime: {
  sql_runtime: {
    no_header: false
  }
}
