# proto-file: github.com/impeccableai/impeccable/proto/workflow/workflow.proto
# proto-message: Task

uuid: "fb9cc6d5-5ebf-42da-ab7d-9aaa2cdef630"
name: "Sleep and passthrough"
description: "Sleep for `time` seconds and then copy input to output"
version: "1.1"
python_script: {
  source: {
    raw: {
      source_uuid: "sleep_pass.py"
      source_name: "sleep_pass.py"
    }
  }
}
inputs: {
  id: "bb"
  name: "input"
  data_kind: FS_FILE
}
outputs: {
  id: "aa"
  name: "output"
  data_kind: FS_FILE
}
default_runtime: {
  python_script_runtime: {
    docker_image: "python:latest"
    command: "python {{ script_path }} {{ input }} {{ output }}"
  }
  new_parameters: {
    key: "time"
    value: {
      optional: false
      value: "60"
    }
  }
}