# proto-file: github.com/impeccableai/impeccable/proto/workflow/workflow.proto
# proto-message: Task

uuid: "010fde64-193a-47cb-b328-c685cd37c897"
name: "Concat files"
description: "This Task concatenates multiple input files into a single output file. The input files are specified as command line arguments using the \"inputs\" flag. The output file is specified using the \"o\" or \"out_file\" flag. The Task reads every file's contents line by line and writes them to the output file."
version: "1.0"
python_script: {
  source: {
    raw: {
      source_uuid: "concat.py"
      source_name: "script.py"
    }
  }
}
inputs: {
  id: "bb"
  name: "inputs"
  data_kind: FS_FILE
  multiple: true
}
outputs: {
  id: "aa"
  name: "output"
  data_kind: FS_FILE
}
default_runtime: {
  python_script_runtime: {
    docker_image: "python:latest"
    command: "python {{ script_path }} {{ inputs }} -o {{ output }}"
  }
}