# proto-file: github.com/impeccableai/impeccable/proto/workflow/workflow.proto
# proto-message: Task

uuid: "d38f9ce0-2789-4b55-9261-11c18bc59d9c"
name: "Drop columns from CSV file"
description: "This Task removes specified columns from a CSV file. The input file is specified with the `--input` flag, and the output file is specified with the `--output` flag. The columns to be removed can be specified by their indices or names using the `--drop_columns` flag. The delimiter and whether the file has a header or not can also be specified."
version: "1.1"
python_script: {
  source: {
    raw: {
      source_uuid: "drop_columns.py"
      source_name: "drop_columns.py"
    }
  }
}
inputs: {
  id: "bb"
  name: "input"
  data_kind: FS_FILE
}
outputs: {
  id: "aa"
  name: "output",
  data_kind: FS_FILE
}
outputs: {
  id: "bb"
  name: "dropped_columns"
  data_kind: FS_FILE
}
default_runtime: {
  python_script_runtime: {
    docker_image: "python:latest"
    command: "python {{ script_path }}"
  }
  new_parameters: {
    key: "delimiter"
    value: {
     optional: false
      value: ","
    }
  }
  new_parameters: {
    key: "drop_columns"
    value: {
     optional: true
      value: ""
    }
  }
  new_parameters: {
    key: "has_header"
    value: {
     optional: false
      value: "True"
    }
  }
}