# proto-file: github.com/impeccableai/impeccable/proto/workflow/workflow.proto
# proto-message: Task

uuid: "a2e37360-61b4-416d-8fe4-a749d861a44d"
name: "Basic metrics"
description: "This Task calculates basic metrics (Precision, Recall, F1, and Accuracy) for binary classification tasks based on input CSV data. The Task reads the input CSV using pandas and calculates the metrics based on the probability column and ground truth column provided by the user."
version: "1.2"
python_script: {
  source: {
    raw: {
      source_uuid: "metrics.py"
      source_name: "metrics.py"
    }
  }
}
inputs: {
  id: "aa"
  name: "dataset"
  data_hint: STRUCTURED_TEXT
  data_kind: FS_FILE
}
outputs: {
  id: "bb"
  name: "metrics_csv"
  data_hint: STRUCTURED_TEXT
  data_kind: FS_FILE
}
default_runtime: {
  python_script_runtime: {
    docker_image: "frolvlad/alpine-python-machinelearning"
    command: "python {{ script_path }} {{ dataset }} {{ metrics_csv }}"
  }
  new_parameters: {
    key: "prob_column"
    value: {
      optional: true
      value: ""
    }
  }
  new_parameters: {
    key: "prob_column"
    value: {
      optional: true
      value: ""
    }
  }
  new_parameters: {
    key: "y_column"
    value: {
      optional: false
      value: "mean"
    }
  }
  new_parameters: {
    key: "delimiter"
    value: {
      optional: false
      value: ","
    }
  }
}