# proto-file: github.com/impeccableai/impeccable/proto/workflow/workflow.proto
# proto-message: Task

uuid: "f66fba8a-5c22-4333-a094-883b039d417f"
name: "Split Train/Test sets"
description: "This Task randomly splits a CSV file into train and test sets. The input file is specified using the \"input\" argument. The output train and test set files are specified using the \"train_set\" and \"test_set\" arguments. The user can define the size of the test set using \"test_size\" argument.

The Task uses the random seed to ensure reproducibility. The user can specify the seed using the \"--seed\" flag. If the CSV file has a header, the Task will keep the header in both train and test set files."
version: "1.1"
python_script: {
  source: {
    raw: {
      source_uuid: "split.py"
      source_name: "split.py"
    }
  }
}
inputs: {
  id: "bb"
  name: "input"
  data_kind: FS_FILE
}
outputs: {
  id: "aa"
  name: "train_set"
  data_kind: FS_FILE
}
outputs: {
  id: "bb"
  name: "test_set"
  data_kind: FS_FILE
}
default_runtime: {
  python_script_runtime: {
    docker_image: "python:latest"
    command: "python {{ script_path }} {{ input }} {{ train_set }} {{ test_set }} {{ test_size }} --seed={{ random_seed }}"
  }
  new_parameters: {
    key: "delimiter"
    value: {
      optional: false
      value: ","
    }
  }
  new_parameters: {
    key: "test_size"
    value: {
      optional: false
      value: "0.2"
    }
  }
  new_parameters: {
    key: "random_seed"
    value: {
      optional: false
      value: "42"
    }
  }
  new_parameters: {
    key: "has_header"
    value: {
      optional: false
      value: "True"
    }
  }
}