# proto-file: github.com/impeccableai/impeccable/proto/workflow/workflow.proto
# proto-message: Task

uuid: "train_test_split"
name: "Split Train/Test sets"
description: "Splits (randomly) a CSV file into train and test sets [-h] [--seed SEED] [-d DELIMITER] [-hdr HAS_HEADER] input train_set test_set test_size\n\npositional arguments:\n\tinput\tinput file\n\ttrain_set\ttrain set file\n\ttest_set\ttest set file\n\ttest_size\tsize of the test set\n\noptions:\n\t-h, --help\tshow this help message and exit\n\t--seed SEED\trandom seed\n\t-d DELIMITER, --delimiter DELIMITER\tcolumn delimiter (default: ',')\n\t-hdr HAS_HEADER, --has_header HAS_HEADER\twhether the file has header (default: True)"
version: "1.1"
python_script: {
  source: {
    raw: {
      source_uuid: "split.py"
      source_name: "split.py"
    }
  }
}
inputs: {
  id: "bb"
  name: "input"
  data_kind: FS_FILE
}
outputs: {
  id: "aa"
  name: "train_set"
  data_kind: FS_FILE
}
outputs: {
  id: "bb"
  name: "test_set"
  data_kind: FS_FILE
}
default_runtime: {
  python_script_runtime: {
    docker_image: "python:latest"
    command: "python {{ script_path }} {{ input }} {{ train_set }} {{ test_set }} {{ test_size }} --seed={{ random_seed }}"
  }
  new_parameters: {
    key: "delimiter"
    value: {
      optional: false
      value: ","
    }
  }
  new_parameters: {
    key: "test_size"
    value: {
      optional: false
      value: "0.2"
    }
  }
  new_parameters: {
    key: "random_seed"
    value: {
      optional: false
      value: "42"
    }
  }
  new_parameters: {
    key: "has_header"
    value: {
      optional: false
      value: "True"
    }
  }
}