# proto-file: github.com/impeccableai/impeccable/proto/workflow/workflow.proto
# proto-message: Task

uuid: "template_spark_task"
name: "Template Spark Task"
description: "This Task can be used as a basic template for your own Spark Tasks"
inputs: {
  id: "0"
  name: "input"
  data_kind: FS_FILE
}
outputs: {
  id: "0"
  name: "output"
  data_kind: FS_DIR
}
default_runtime: {
  spark_job_runtime: {
    k8s_runtime: {
      container_image: "impeccableai/spark-py:spark-k8s-bitnami"
    }
    packages: "com.amazonaws:aws-java-sdk-pom:1.11.956"
    packages: "org.apache.hadoop:hadoop-aws:3.3.1"
    executor_instances: 1
    main_app_file: "{{ script_path }}"
    app_arguments: "--input {{ input }} --output {{ output }}"
  }
}
spark_job: {
  source: {
    raw: {
      source_uuid: "job.py"
      source_name: "job.py"
    }
  }
}
