# proto-file: github.com/impeccableai/impeccable/proto/workflow/workflow.proto
# proto-message: Task

uuid: "3291980b-4165-4534-946a-8624361a3ae1"
name: "Failing"
description: "This Task writes the numbers 0 to 14, each on a new line, to a specified output file. After writing these numbers, the Task raises an exception, simulating a bad situation."
python_script: {
  source: {
    raw: {
      source_uuid: "failing.py"
      source_name: "script.py"
    }
  }
}
outputs: {
  id: "aa"
  name: "output"
  data_kind: FS_FILE
}
default_runtime: {
  python_script_runtime: {
    docker_image: "python:alpine"
    command: "python {{ script_path }}"
  }
}