# proto-file: github.com/impeccableai/impeccable/proto/workflow/workflow.proto
# proto-message: Task

uuid: "failing"
name: "failing"
python_script: {
  source: {
    raw: {
      source_uuid: "failing.py"
      source_name: "script.py"
    }
  }
}
outputs: {
  id: "aa"
  name: "output"
  data_kind: FS_FILE
}
default_runtime: {
  python_script_runtime: {
    docker_image: "python:alpine"
    command: "python {{ script_path }}"
  }
}