# proto-file: github.com/impeccableai/impeccable/proto/workflow/workflow.proto
# proto-message: Task

uuid: "5bfcb6d9-e837-4e39-a726-07d466096b4c"
name: "Generator"
description: "This Task generates a file with a specified number of lines, where each line contains an integer from 0 to `size-1`. The size of the output file is determined by the \"size\" parameter. The output file is specified using the \"output\" flag."
version: "1.1"
python_script: {
  source: {
    raw: {
      source_uuid: "generator.py"
      source_name: "script.py"
    }
  }
}
outputs: {
  id: "aa"
  name: "output"
  data_kind: FS_FILE
}
default_runtime: {
  python_script_runtime: {
    docker_image: "python:alpine"
    command: "python {{ script_path }}"
  }
  new_parameters: {
    key: "size"
    value: {
      optional: false
      value: "15"
    }
  }
}