# proto-file: github.com/impeccableai/impeccable/proto/workflow/workflow.proto
# proto-message: Task

uuid: "468c3541-d47d-49b5-a390-b16bfc080d08"
name: "s3 dir generator"
python_script: {
  source: {
    raw: {
      source_uuid: "source"
      source_name: "script.py"
    }
  }
}
outputs: {
  id: "a"
  name: "output"
  data_kind: S3_DIR
}
default_runtime: {
  python_script_runtime: {
    docker_image: "wookeshi/boto3:alpine"
    command: "{{ script_path }}/entrypoint.sh {{ script_path }}"
  }
}