# proto-file: github.com/impeccableai/impeccable/proto/workflow/workflow.proto
# proto-message: Task

uuid: "12877024-280b-44d9-a7c3-1a025380a1b1"
name: "Random Python"
nondeterministic: true
python_script: {
  source: {
    raw: {
      source_uuid: "source.py"
      source_name: "script.py"
    }
  }
}
outputs: {
  id: "a"
  name: "output"
  data_kind: FS_FILE
}
default_runtime: {
  python_script_runtime: {
    docker_image: "python:alpine"
    command: "python {{ script_path }}"
  }
}