# proto-file: github.com/impeccableai/impeccable/proto/workflow/workflow.proto
# proto-message: Task

uuid: "2890a481-372c-4053-a635-a420905b3f1e"
name: "Dir list"
description: "This Task lists file names in a directory and writes them to an output file. The input directory is specified using the \"dir\" flag, and the output file is specified using the \"output\" flag."
python_script: {
  source: {
    raw: {
      source_uuid: "script.py"
      source_name: "script.py"
    }
  }
}
inputs: {
  id: "aa"
  name: "dir"
  data_kind: FS_DIR
}
outputs: {
  id: "bb"
  name: "output"
  data_kind: FS_FILE
}
default_runtime: {
  python_script_runtime: {
    docker_image: "python:alpine"
    command: "python {{ script_path }}"
  }
}