# proto-file: github.com/impeccableai/impeccable/proto/workflow/workflow.proto
# proto-message: Task

uuid: "fede8785-3742-4c35-a54b-dda8ebbbc350"
name: "Stack files"
description: "This Task stacks columns from multiple input files into a single output file. The input files are specified as command line arguments using the \"inputs\" flag. The output file is specified using the \"o\" or \"out_file\" flag. The Task reads every file's contents line by line, and writes them as a single line to the output file."
version: "1.1"
python_script: {
  source: {
    raw: {
      source_uuid: "stack.py"
      source_name: "stack.py"
    }
  }
}
inputs: {
  id: "bb"
  name: "inputs"
  data_kind: FS_FILE
  multiple: true
}
outputs: {
  id: "aa"
  name: "output"
  data_kind: FS_FILE
}
default_runtime: {
  python_script_runtime: {
    docker_image: "python:latest"
    command: "python {{ script_path }} {{ inputs }} -o {{ output }}"
  }
  new_parameters: {
    key: "delimiter"
    value: {
      optional: false
      value: ","
    }
  }
}