# proto-file: github.com/impeccableai/impeccable/proto/workflow/workflow.proto
# proto-message: Task

uuid: "fdd0f530-8026-471c-b903-945faa4b23b3"
name: "Template Python Task"
description: "This Task can be used as a basic template for your own Python Tasks"
tags: "template"
inputs: {
  id: "0"
  name: "input"
  data_kind: FS_FILE
}
outputs: {
  id: "0"
  name: "output"
  data_kind: FS_FILE
}
python_script: {
  source: {
    raw: {
      source_uuid: "script.py"
      source_name: "script.py"
    }
  }
}
default_runtime: {
  new_parameters: {
    key: "parameter"
    value: {
     optional: false
      value: "value"
    }
  }
  python_script_runtime: {
    docker_image: "python:alpine"
    command: "python {{ script_path }}"
  }
}
