# proto-file: github.com/impeccableai/impeccable/proto/workflow/workflow.proto
# proto-message: Task

uuid: "143673ba-179f-42e6-9d03-aa716e2a20f4"
name: "Classification Metrics"
description: "This Task computes metrics for classification tasks, such as precision, recall, F1 score, and accuracy. It reads a dataset in CSV format and calculates these metrics for each unique class in the dataset. The results are written to an output CSV file."
version: "1.2"
python_script: {
  source: {
    raw: {
      source_uuid: "metrics.py"
      source_name: "script.py"
    }
  }
}
inputs: {
  id: "aa"
  name: "dataset"
  data_hint: STRUCTURED_TEXT
  data_kind: FS_FILE
}
outputs: {
  id: "bb"
  name: "metrics_csv"
  data_hint: STRUCTURED_TEXT
  data_kind: FS_FILE
}
default_runtime: {
  python_script_runtime: {
    docker_image: "frolvlad/alpine-python-machinelearning"
    command: "python {{ script_path }} {{ dataset }} {{ metrics_csv }}"
  }
  new_parameters: {
    key: "predicted_column"
    value: {
      optional: true
      value: ""
    }
  }
  new_parameters: {
    key: "y_column"
    value: {
      optional: false
      value: "mean"
    }
  }
  new_parameters: {
    key: "delimiter"
    value: {
      optional: false
      value: ","
    }
  }
}