# proto-file: github.com/impeccableai/impeccable/proto/workflow/workflow.proto
# proto-message: Task

uuid: "555c3c42-01b5-43ff-8834-6767f5a5230b"
name: "Fill NaNs in column"
description: "This Task fills missing (NaN) values in a specified column of a CSV file. The method of filling can be chosen from the following modes: mean, min, max, or const (constant value). The input and output CSV files are specified as command line arguments, as well as the column to be filled and the mode of filling."
version: "1.1"
python_script: {
  source: {
    raw: {
      source_uuid: "fill.py"
      source_name: "fill.py"
    }
  }
}
inputs: {
  id: "aa"
  name: "input_csv"
  data_hint: STRUCTURED_TEXT
  data_kind: FS_FILE
}
outputs: {
  id: "bb"
  name: "output_csv"
  data_hint: STRUCTURED_TEXT
  data_kind: FS_FILE
}
default_runtime: {
  python_script_runtime: {
    docker_image: "python:latest"
    command: "python {{ script_path }} {{ input_csv }} {{ output_csv }} {{ column }}"
  }
  new_parameters: {
    key: "column"
    value: {
      optional: true
      value: ""
    }
  }
  new_parameters: {
    key: "mode"
    value: {
      optional: false
      value: "mean"
    }
  }
  new_parameters: {
    key: "value"
    value: {
      optional: false
      value: "0"
    }
  }
  new_parameters: {
    key: "delimiter"
    value: {
      optional: false
      value: ","
    }
  }
}