# proto-file: github.com/impeccableai/impeccable/proto/workflow/workflow.proto
# proto-message: Task

uuid: "eecb9c91-a006-4a01-986a-9a2c59024625"
name: "Remove duplicates [SPARK]"
inputs: {
  id: "0"
  name: "input"
  data_hint: STRUCTURED_TEXT
  data_kind: FS_FILE
}
outputs: {
  id: "0"
  name: "output"
  data_hint: STRUCTURED_TEXT
  data_kind: FS_DIR
}
version: "1.1.0"
default_runtime: {
  spark_job_runtime: {
    k8s_runtime: {
      container_image: "impeccableai/spark-py:spark-k8s-bitnami"
    }
    packages: "com.amazonaws:aws-java-sdk-pom:1.11.956"
    packages: "org.apache.hadoop:hadoop-aws:3.3.1"
    executor_instances: 1
    main_app_file: "{{ script_path }}"
    app_arguments: "--input {{ input }} --output {{ output }}"
  }
}
spark_job: {
  source: {
    raw: {
      source_uuid: "dedup.py"
      source_name: "dedup.py"
    }
  }
}
