# proto-file: github.com/impeccableai/impeccable/proto/workflow/workflow.proto
# proto-message: Task

uuid: "9516a9c9-988b-4e04-88f2-12c13b6ccdee"
name: "Dual Reader"
description: "This Task reads two files containing lists of integers and prints pairs of integers from the two files line by line. It stops when the shorter file is exhausted."
python_script: {
  source: {
    raw: {
      source_uuid: "reader.py"
      source_name: "script.py"
    }
  }
}
inputs: {
  id: "da"
  name: "a"
  data_kind: FS_FILE
}
inputs: {
  id: "db"
  name: "b"
  data_kind: FS_FILE
}
default_runtime: {
  python_script_runtime: {
    docker_image: "python:alpine"
    command: "python {{ script_path }}"
  }
}