# proto-file: github.com/impeccableai/impeccable/proto/workflow/workflow.proto
# proto-message: Task

uuid: "5471829c-0631-4879-8483-316332ab61b0"
name: "family - child task 2"
version: "1.1.1"
parent_uuid: "family_00"
state: TASK_STATE_ACTIVE
python_script: {
  source: {
    raw: {
      source_uuid: "generator.py"
      source_name: "script.py"
    }
  }
}
outputs: {
  id: "aa"
  name: "output"
  data_kind: FS_FILE
}
default_runtime: {
  python_script_runtime: {
    docker_image: "python:alpine"
    command: "python {{ script_path }}"
  }
}