# proto-file: github.com/impeccableai/impeccable/proto/workflow/workflow.proto
# proto-message: Task

uuid: "reader"
name: "reader"
python_script: {
  source_uuid: "reader.py"
  source_name: "script.py"
  source: {
    raw: {
      source_uuid: "reader.py"
      source_name: "script.py"
    }
  }
}
inputs: {
  id: "da"
  name: "a"
  data_kind: FS_FILE
}
inputs: {
  id: "db"
  name: "b"
  data_kind: FS_FILE
}
default_runtime: {
  python_script_runtime: {
    docker_image: "python:alpine"
    command: "python {{ script_path }}"
  }
}