# proto-file: github.com/impeccableai/impeccable/proto/workflow/workflow.proto
# proto-message: Task

uuid: "21408e97-ce77-491f-82e4-675e1b541010"
name: "Reader"
description: "This Task reads input file line by line and prints it's content to standard output."
python_script: {
  source: {
    raw: {
      source_uuid: "reader.py"
      source_name: "script.py"
    }
  }
}
inputs: {
  id: "da"
  name: "file"
  data_kind: FS_FILE
}
default_runtime: {
  python_script_runtime: {
    docker_image: "python:alpine"
    command: "python {{ script_path }} {{ file }}"
  }
}