# proto-file: github.com/impeccableai/impeccable/proto/workflow/workflow.proto
# proto-message: Task

uuid: "963c6601-a73c-4b74-acc3-a086ddf09b19"
name: "Python Task with entrypoint"
description: "Demonstrates how to use an entrypoint to run pip install"
python_script: {
  source: {
    raw: {
      source_uuid: "entrypoint_python"
      source_name: "entrypoint_python"
    }
  }
}
default_runtime: {
  python_script_runtime: {
    docker_image: "python:latest"
    command: "sh {{ script_path }}/entrypoint.sh --arg={{ arg }}"
  }
  new_parameters: {
    key: "arg"
    value: {
      optional: false
      value: "arg"
    }
  }
}