# proto-file: github.com/impeccableai/impeccable/proto/workflow/workflow.proto
# proto-message: Task

uuid: "c9fd0c59-05a7-48a7-82a1-af1666295573"
name: "basic reader"
python_script: {
  source_uuid: "reader.py"
  source_name: "script.py"
  source: {
    raw: {
      source_uuid: "reader.py"
      source_name: "script.py"
    }
  }
}
inputs: {
  id: "bb"
  name: "input"
  data_hint: DATA_HINT_NONE
  data_kind: FS_FILE
}
default_runtime: {
  python_script_runtime: {
    docker_image: "python:alpine"
    command: "python {{ script_path }}"
  }
}