# proto-file: github.com/impeccableai/impeccable/proto/workflow/workflow.proto
# proto-message: Task

uuid: "sql_query"
name: "SQL Query"
sql: {
  source: {
    raw: {
      source_uuid: "query.sql"
      source_name: "query.sql"
    }
  }
}
outputs: {
  id: "0"
  name: "output"
  data_kind: FS_FILE
  data_hint: STRUCTURED_TEXT
}
default_runtime: {
  sql_runtime: {
    no_header: false
  }
  new_parameters: {
    key: "parameter"
    value: {
      optional: false
      value: "value"
    }
  }
}