# proto-file: github.com/impeccableai/impeccable/proto/workflow/workflow.proto
# proto-message: Task

uuid: "14af676e-701f-4809-9cbb-9bd435abbef9"
name: "SQL Query"
description: "This Task can be used as a basic template for your own SQL Tasks"
sql: {
  source: {
    raw: {
      source_uuid: "query.sql"
      source_name: "query.sql"
    }
  }
}
outputs: {
  id: "0"
  name: "data"
  data_kind: FS_FILE
  data_hint: STRUCTURED_TEXT
}
default_runtime: {
  new_parameters: {
    key: "table_name"
    value: {
     optional: false
      value: "table_name"
    }
  }
  sql_runtime: {
    no_header: false
  }
}