# proto-file: github.com/impeccableai/impeccable/proto/workflow/workflow.proto
# proto-message: Task

uuid: "fe3e1e2f-d6a0-45ba-a11a-6677fcaba2fb"
name: "s3 generator"
python_script: {
  source: {
    raw: {
      source_uuid: "source"
      source_name: "script.py"
    }
  }
}
outputs: {
  id: "a"
  name: "output"
  data_kind: S3_FILE
}
default_runtime: {
  python_script_runtime: {
    docker_image: "wookeshi/boto3:alpine"
    command: "{{ script_path }}/entrypoint.sh {{ script_path }}"
  }
}