# proto-file: github.com/impeccableai/impeccable/proto/workflow/workflow.proto
# proto-message: Task

uuid: "53e115e3-9f0c-4c86-929e-905a26e62c87"
name: "Print args"
description: "This Task prints the input file names and an additional argument provided as command line inputs. The input files are specified as command line arguments using the \"inputs\" flag. The additional argument is specified using the "arg" flag."
version: "1.1"
python_script: {
  source: {
    raw: {
      source_uuid: "print.py"
      source_name: "print.py"
    }
  }
}
inputs: {
  id: "bb"
  name: "inputs"
  data_kind: FS_FILE
}
default_runtime: {
  python_script_runtime: {
    docker_image: "python:latest"
    command: "python {{ script_path }} {{ inputs }}"
  }

  new_parameters: {
    key: "arg"
    value: {
      optional: false
      value: "default"
    }
  }
}